### ISSUE TITLE
Unicode page names do not work

### ISSUE THREAD

**Issue by v2e** [frozeman/feindura-flat-file-cms#14]
Hello!
  I discovered Feindura only recently, when I was looking for a CMS for my small page. It looks nice and well designed to me, however I found some disadvantages which prevent me from using it for my tasks. I thought it would be useful to report them.
  First of all, I want to build a multi-language website with the Russian as a primary language. However, Feindura does not let me choose the 'latin' page name for a page with a name in Russian. I believe, it would be convenient to have an ability to edit a link to the page by hand in such cases (although, the Unicode URLs are allowed nowadays as well, if I'm not mistaking).
  The second disadvantage is the flash-based file upload only. It is inconvenient for the users like me, that do not use Flash-plugin. I wrote some of my thoughts about this problem in the 'Ideas' section here: https://getsatisfaction.com/feindura/topics/flash_free_file_upload

  Unless these two issues are fixed or I find a way to work-around them, I cannot use Feindura for my web-site. Which is a pity, because I like Feindura look&feel very much!

  Regards,
    Vladimir

**Comment by frozeman** [comment]
Hi,

thanks you for your interest in feindura!
the feature t edit links, is quite important ts true, i didnt thought abaout that until i had a page name with chinese characters :)

i will implement this into feindura 2.0

which version your are using right now?
do you want to try the new 2.o version? then download the feindura 2.0 development branch.
delete the "doc" folder, because you dont need it and do not copy the VERSION file, if you want to update. then run the update.php.

this version has the new multiple language feature (but still not unicode page names... :( )

the flash uploader is a good point, but because its the filemanager, which is an extra project, i didn't changed so much in there.. but i planned on using a non flahs upload.. (just didn't change it yet,but will take some time i guess)

i hope youre still on feindura and will use it. take a look at the feindura facebook page: http://facebook.com/feindura.cms

thanks for you ideas!

fabian

**Comment by frozeman** [comment]
you can deactivate speaking urls for now, and when the new unicode urls feature is implemented, you can add turn it back on..

**Comment by v2e** [comment]
Hello!
I'm very glad to hear that you are currently working actively on a new version!
Currently I'm trying to establish my website using Feindura v.1.1.6, but I think, I'll try the development version as well.

Speaking of the "speaking urls", as far as I understand, Feindura uses .htaccess file for that purpose. If that is true, it means that the "speaking urls" may only be used with Apache web-server, am I right? But what about other web-servers (like the Lighttpd that I use)?

Thank you!
  Vladimir

**Comment by frozeman** [comment]
If you aren't using speaking urls the. You shouldnt have any problems with Unicode page titles, or may e I misunderstood your problem. If so can you send me an screenshot by mail? Fabian at feindura.org

Speaking urls is currently only support on a apache server because of htaccess :(
Because I have only apache servers iam only able to implement this feature. 

If you have any idea how to Implement speaking urls on other servers please send me the information. 

Fabian

**Comment by v2e** [comment]
> If you aren't using speaking urls the. You shouldnt have any problems with Unicode page titles

Yes, of course. It works fine without "speaking URLs".

> If you have any idea how to Implement speaking urls on other servers please send me the information.
> Well, as far as I know, there are several ways of implementing [more or less] speaking URLs.
1.  Create static HTML files with the "ready-to-use" content. In this case the URLs would look like this:
   mydomain.org/category1/page1.html
   
   As far as I know, there are some CMSs that use such approach. The static HTML files are generated every time the site administrator edits the page, and are served as a static contend by a web-server after that. However, it imposes some limits on pages contents, since one cannot make the web-server return the automatically refresing or changing content. For example, if you administrate an internet radio, you have to re-generate the static HTML files for every playing song instead of doing it only upon request.
2.  Create the appropriate rewrite rules for web-server (in .htaccess files in Apache's case). In such case the URLs would look like this:
   mydomain.org/catergory1/page1
   
   In this case the URLs are probably the most beautiful, since they do not contain any file extensions like .php or .html or .cgi
3.  Create the "rewrite by hand" in some primary PHP file that returns the requested page.
   mydomain.org/somename.php/category1/page1
   
   A popular wiki engine called DokuWiki uses such approach among other means to obtain a somewhat more nice-looking and intuitively understandable URL names. It is a good compromise, I believe. At least, such URLs are much more pretty and readable then something like "mydomain.org/somename.php?category=15&page=367&lang=eng&id=33745227&browser=Midori".

Speaking of different web-servers, I'm not sure about "nginx", but with "lighttpd" the situation is the following:
  All the configuration files are usually stored in "/etc/lighttpd/" directory with write access enable for root only.  There is a possibility to provide a separate configuration file for every virtual server howerver. Those files are stored somewhere inside "/etc/lighttpd/" as well. 
  So, in order to utilize the .htaccess files on a system with lighttpd as the only web-server, it is possible to run some kind of cron job that scans the given directory for .htaccess files and adds the corresponding rules into the config files in "/etc/lighttpd/..."
  In such way the administrator is able to get the "speaking URLs" through .htaccess files working in an hour after their last modification (since the most frequent cron job is executed hourly). It is also a solution, however not as "clean" as one would wish, and depends on the administrator's preferences. As for me, I do not do that, because it seems not worth spending time for me and because I more or less like the solution #3 described above.

  Returning to Feindura, I would suggest adding the third variant of "speaking URLs" to Feindura. What do you thing about that? It seems not to be very hard to implement, or is it?

  Regards,
    Vladimir

**Comment by frozeman** [comment]
hi, thanks for your ideas.

feindura uses currently the second approach with an .htaccess file, beacuse it allows to fully customize your website and your content is always uptodate.

concerning the first approach:
this would be a problem, because this would limit the way you can customize your pages. you may want to have a sidebar on one page and a sub menu on another, so with php you can do this easily by asking:

```
  if($feindura->category == 2) .... show the sidebar
```

this wouldnt work in this case, when you have static pages.
There is already a caching feature in the new version, which generates static pages out of dynamic ones, but dont create the folder structure necessary for speaking urls.

the disadvantage of the last approach is that your server would have a mess of files.
currently you only have you index.php and your cms folder as the necessary parts of your website, everything else is optional or generated automatically inside the cmd folders.

this way you have a clean server environment and can make changes really fast.

you could implement the third way yourself pointing your links  to some other php pages and add the feindura code in there again. but it wouldnt be dynamic and be close to a static html website.

the current approach generates you clean speaking urls, and when you have a multilanguage website then it even adds you:

```
  http://somewebsite.com/en/category/shoes/addidas
```

and you now can even could change the "en" to "ru" and it would how you the russian version of that page.
so its kind of flexible.

you could also use:

```
 http://somewebsite.com/en/page/addidas
```

and you would get to the same page...

so aim currently quite happy with the current speaking urls implementation.
but i would like to transfer this approach also to other server types.

when you say that you can let the .htacces get implemented into an config file of an lighttpd server, then this woul be absolutely fine, beacud you only activate the speaking url feature ones, and it will work always after no matter how many pages you add.

did you try the 2.0 beta?

fabian

**Comment by frozeman** [comment]
the latest commit, has now an non flash uploader in the filemanager.

https://github.com/frozeman/feindura-flat-file-cms/commit/c9ccea24bb3498387ffb2e868439dd0e1ca5be65

**Comment by v2e** [comment]
Hello!
I downloaded the latest snapshot of the Feindura development version. It looks impressive! :)
Thanks for such quick implementation of the flash-free files upload. That's great. However, I cannot find a way to create the pages in a new Feindura. 
  I downloaded the ZIP-archive and unpacked it, but there were no sample pages. And I cannot find a button to create a new page, while Feindura constantly gives me a warning that the main (home) page is not set.

  Regards,
    Vladimir

**Comment by frozeman** [comment]
hi yeah the version from github isn't ready for use.. so you have to some things manually sorry for that.

i can send you the current version by mail including a simple demo page..
i also implemented the editing of the page links, but this works only if you activated pretty urls..

**Comment by frozeman** [comment]
can you send me a mail to fabian @ feindura.org ? so i can send you the demo files.

fabian
